{
 "title": "Wialon IPS Exporter",
 "tags": [ "wialon" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "src_ip",
    "label": "Source IP",
    "query": {
     "query": "label_values(wialon_ips_packets_total,src_ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active streams",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wialon_ips_streams_by_ip_size{src_ip=~\"$src_ip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "wialon_ips_streams_by_ip_size{src_ip=~\"$src_ip\"}",
     "legendFormat": "{{src_ip}} - {{dst_ip}}"
    }
   ]
  },
  { "title": "Packets stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Packet by types",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(wialon_ips_packets_total{src_ip=~\"$src_ip\"}[$__rate_interval])",
     "legendFormat": "{{dst_ip}} - {{type}}"
    }
   ]
  },
  {
   "title": "All packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(wialon_ips_raw_packets_total[$__rate_interval])",
     "legendFormat": "all packets"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(wialon_ips_parse_errors_total[$__rate_interval])",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}